# Generated by Django 3.2.2 on 2021-05-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_auto_20210513_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Type', models.CharField(blank=True, max_length=40, null=True)),
                ('S_date', models.DateField(blank=True, null=True)),
                ('FM_ID', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.fmstock')),
                ('RM_ID', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.rawmaterial')),
            ],
        ),
    ]
