# Generated by Django 3.2.2 on 2021-05-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='UFcoilID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apex.ufmstock'),
        ),
    ]
