# Generated by Django 3.2.2 on 2021-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0004_sale_ufcoilid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='register',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
