# Generated by Django 3.2.2 on 2021-05-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0005_alter_logtable_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtable',
            old_name='register',
            new_name='register_id',
        ),
    ]
