# Generated by Django 3.2.2 on 2021-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0006_rename_register_logtable_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialitemuseperday',
            name='EPD_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='Log_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='RM_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
