# Generated by Django 3.2.2 on 2021-05-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0007_auto_20210515_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtable',
            old_name='TableName',
            new_name='Table_id',
        ),
        migrations.RenameField(
            model_name='logtable',
            old_name='username',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='essentialitemuseperday',
            name='EPD_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='Log_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='RM_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
