# Generated by Django 3.2.2 on 2021-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0010_auto_20210519_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='UserName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
