# Generated by Django 3.2.2 on 2021-05-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0011_register_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Last_Name',
        ),
    ]
