# Generated by Django 3.2.2 on 2021-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0012_auto_20210519_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='register',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
