# Generated by Django 3.2.2 on 2021-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0013_auto_20210519_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Stock',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
