# Generated by Django 3.2.2 on 2021-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0015_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='Product_Quantity',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='Product_Size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='Product_Thickness',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='Table_Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
