# Generated by Django 3.2.2 on 2021-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0016_auto_20210520_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=40, null=True)),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
