# Generated by Django 3.2.2 on 2021-05-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0017_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='RM_Grade',
            field=models.CharField(blank=True, choices=[('202Q', '202Q'), ('304Q', '304Q'), ('316Q', '316Q')], max_length=40, null=True),
        ),
    ]
