# Generated by Django 3.2.2 on 2021-05-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0019_auto_20210526_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleted_tables',
            old_name='table_id',
            new_name='table_name',
        ),
    ]
