# Generated by Django 3.2.2 on 2021-05-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0020_rename_table_id_deleted_tables_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='stock_count',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
