# Generated by Django 3.2.2 on 2021-05-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0021_auto_20210528_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrape',
            name='FM_ID',
        ),
        migrations.RemoveField(
            model_name='scrape',
            name='RM_ID',
        ),
        migrations.AddField(
            model_name='scrape',
            name='s_weight',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='t_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
