# Generated by Django 3.2.2 on 2021-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0023_timmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufmstock',
            name='UFM_type',
            field=models.DateField(blank=True, null=True),
        ),
    ]
