# Generated by Django 3.2.2 on 2021-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0024_ufmstock_ufm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufmstock',
            name='UFM_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
