# Generated by Django 3.2.2 on 2021-06-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0025_alter_ufmstock_ufm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='seen',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
