# Generated by Django 3.2.2 on 2021-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0026_messages_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='delete_access',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
