# Generated by Django 3.2.2 on 2021-06-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0027_register_delete_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Product_Quantity',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Product_Size',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Product_Thickness',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Table_Name',
        ),
    ]
